name: "elixir-nif-peer-example"

on:
  push:
    branches:
      - main
    paths:
      - elixir-nif-peer-example/Dockerfile
      - .github/workflows/elixir-nif-peer-example.yml
  workflow_dispatch:
    inputs:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: elixir-nif-peer-example
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/elixir-nif-peer-example:latest
            ghcr.io/${{ github.repository }}/elixir-nif-peer-example:${{ github.sha }}