# name: "elixir-postgres-cluster-example"

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - elixir-postgres-cluster-example/Dockerfile
#       - .github/workflows/elixir-postgres-cluster-example.yml
#   workflow_dispatch:
#     inputs:

# jobs:
#   build-and-push:
#     strategy:
#       matrix:
#         target: [build, run]
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         name: Checkout
#         uses: actions/checkout@v4
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - 
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - 
#         name: Login to GHCR
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - 
#         name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           context: elixir-postgres-cluster-example
#           platforms: |
#             linux/amd64
#             linux/arm64
#           target: ${{ matrix.target }}
#           tags: |
#             ghcr.io/${{ github.repository }}/elixir-postgres-cluster-example/${{ matrix.target }}:latest
#             ghcr.io/${{ github.repository }}/elixir-postgres-cluster-example/${{ matrix.target }}:${{ github.sha }}
